// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystemFightNight.Data;

#nullable disable

namespace TicketingSystemFightNight.Migrations.Vjezba
{
    [DbContext(typeof(VjezbaDbContext))]
    [Migration("20260518103030_SyncVjezbaSchema")]
    partial class SyncVjezbaSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("TicketingSystemFightNight.Models.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenedYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arenas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ulica Grada Vukovara 269a",
                            Capacity = 15000,
                            City = "Zagreb",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8206),
                            IsIndoor = true,
                            Name = "Arena Zagreb",
                            OpenedYear = 2008
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ulica Domovinskog rata 2",
                            Capacity = 12000,
                            City = "Split",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8210),
                            IsIndoor = false,
                            Name = "Arena Split",
                            OpenedYear = 2019
                        },
                        new
                        {
                            Id = 3,
                            Address = "Trg Riječke rezolucije 2",
                            Capacity = 10000,
                            City = "Rijeka",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8213),
                            IsIndoor = true,
                            Name = "Arena Rijeka",
                            OpenedYear = 2014
                        },
                        new
                        {
                            Id = 4,
                            Address = "Štefanova cesta 6",
                            Capacity = 14000,
                            City = "Ljubljana",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8216),
                            IsIndoor = true,
                            Name = "Ljubljana Arena",
                            OpenedYear = 2002
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseTicketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseTicketPrice = 250m,
                            City = "Zagreb",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8263),
                            Date = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Jones vs Gustafsson",
                            Name = "UFC Fight Night Zagreb",
                            OrganizationId = 1,
                            TicketsSold = 12850,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseTicketPrice = 180m,
                            City = "Split",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8286),
                            Date = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Ngannou vs Miocic",
                            Name = "UFC Fight Night Split",
                            OrganizationId = 1,
                            TicketsSold = 9800,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            BaseTicketPrice = 150m,
                            City = "Rijeka",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8292),
                            Date = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Cormier vs Gustafsson",
                            Name = "UFC Fight Night Rijeka",
                            OrganizationId = 1,
                            TicketsSold = 7600,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 3
                        },
                        new
                        {
                            Id = 4,
                            BaseTicketPrice = 220m,
                            City = "Ljubljana",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8298),
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Batinić vs Nedoh",
                            Name = "FNF 29 Ljubljana",
                            OrganizationId = 3,
                            TicketsSold = 5600,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.FightOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FightOrganizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8147),
                            Name = "UFC"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8157),
                            Name = "KSW"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8160),
                            Name = "FNC"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8162),
                            Name = "BELLATOR"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8166),
                            Name = "ONE FC"
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Fighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("WeightClassId");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8220),
                            Losses = 1,
                            Name = "Jon Jones",
                            Nickname = "Bones",
                            OrganizationId = 1,
                            WeightClassId = 7,
                            Wins = 26
                        },
                        new
                        {
                            Id = 2,
                            Country = "Cameroon",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8229),
                            Losses = 3,
                            Name = "Francis Ngannou",
                            Nickname = "The Predator",
                            OrganizationId = 1,
                            WeightClassId = 8,
                            Wins = 16
                        },
                        new
                        {
                            Id = 3,
                            Country = "Sweden",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8234),
                            Losses = 7,
                            Name = "Alexander Gustafsson",
                            Nickname = "The Mauler",
                            OrganizationId = 1,
                            WeightClassId = 7,
                            Wins = 18
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8238),
                            Losses = 3,
                            Name = "Daniel Cormier",
                            Nickname = "DC",
                            OrganizationId = 1,
                            WeightClassId = 7,
                            Wins = 22
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8242),
                            Losses = 4,
                            Name = "Stipe Miocic",
                            Nickname = "The Croatian Sensation",
                            OrganizationId = 1,
                            WeightClassId = 8,
                            Wins = 20
                        },
                        new
                        {
                            Id = 6,
                            Country = "Brazil",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8246),
                            Losses = 5,
                            Name = "Amanda Nunes",
                            Nickname = "The Lioness",
                            OrganizationId = 1,
                            WeightClassId = 2,
                            Wins = 21
                        },
                        new
                        {
                            Id = 7,
                            Country = "Slovenia",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8250),
                            Losses = 2,
                            Name = "Matej Batinić",
                            Nickname = "The Slovenian Storm",
                            OrganizationId = 3,
                            WeightClassId = 6,
                            Wins = 18
                        },
                        new
                        {
                            Id = 8,
                            Country = "Slovenia",
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8254),
                            Losses = 3,
                            Name = "Jakob Nedoh",
                            Nickname = "The Ljubljana Lion",
                            OrganizationId = 3,
                            WeightClassId = 6,
                            Wins = 17
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Championship")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fighter1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fighter2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Fighter1Id");

                    b.HasIndex("Fighter2Id");

                    b.HasIndex("WeightClassId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Championship = true,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8306),
                            EventId = 1,
                            Fighter1Id = 1,
                            Fighter2Id = 3,
                            Referee = "Herb Dean",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClassId = 7
                        },
                        new
                        {
                            Id = 2,
                            Championship = false,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8319),
                            EventId = 2,
                            Fighter1Id = 2,
                            Fighter2Id = 5,
                            Referee = "John McCarthy",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClassId = 8
                        },
                        new
                        {
                            Id = 3,
                            Championship = false,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8324),
                            EventId = 3,
                            Fighter1Id = 4,
                            Fighter2Id = 3,
                            Referee = "Yves Lavigne",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClassId = 7
                        },
                        new
                        {
                            Id = 4,
                            Championship = false,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8328),
                            EventId = 4,
                            Fighter1Id = 7,
                            Fighter2Id = 8,
                            Referee = "Slavko Kosanović",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClassId = 6
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVip")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.TicketShopModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TicketShopModels");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8337),
                            Email = "admin@example.com",
                            IsVip = true,
                            LoyaltyPoints = 150,
                            MemberLevel = "Administrator",
                            Name = "admin",
                            Phone = "+385911234567"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1988, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8347),
                            Email = "john.doe@example.com",
                            IsVip = false,
                            LoyaltyPoints = 200,
                            MemberLevel = "Regular User",
                            Name = "john_doe",
                            Phone = "+385912345678"
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.WeightClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeightClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8174),
                            Name = "Flyweight"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8180),
                            Name = "Bantamweight"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8182),
                            Name = "Featherweight"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8185),
                            Name = "Lightweight"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8187),
                            Name = "Welterweight"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8190),
                            Name = "Middleweight"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8192),
                            Name = "LightHeavyweight"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 18, 10, 30, 29, 709, DateTimeKind.Utc).AddTicks(8195),
                            Name = "Heavyweight"
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Cart", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Event", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.FightOrganization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.Arena", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Fighter", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.FightOrganization", "Organization")
                        .WithMany("Fighters")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.WeightClass", "WeightClass")
                        .WithMany("Fighters")
                        .HasForeignKey("WeightClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("WeightClass");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Match", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.Event", "Event")
                        .WithMany("Matches")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.Fighter", "Fighter1")
                        .WithMany("MatchesAsFighter1")
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.Fighter", "Fighter2")
                        .WithMany("MatchesAsFighter2")
                        .HasForeignKey("Fighter2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.WeightClass", "WeightClass")
                        .WithMany("Matches")
                        .HasForeignKey("WeightClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Fighter1");

                    b.Navigation("Fighter2");

                    b.Navigation("WeightClass");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Ticket", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.Cart", "Cart")
                        .WithMany("Tickets")
                        .HasForeignKey("CartId");

                    b.HasOne("TicketingSystemFightNight.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Arena", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Cart", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Event", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.FightOrganization", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Fighters");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Fighter", b =>
                {
                    b.Navigation("MatchesAsFighter1");

                    b.Navigation("MatchesAsFighter2");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.User", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.WeightClass", b =>
                {
                    b.Navigation("Fighters");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
