// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystemFightNight.Data;

#nullable disable

namespace TicketingSystemFightNight.Migrations.Vjezba
{
    [DbContext(typeof(VjezbaDbContext))]
    partial class VjezbaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("TicketingSystemFightNight.Models.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenedYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Arenas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ulica Grada Vukovara 269a",
                            Capacity = 15000,
                            City = "Zagreb",
                            IsIndoor = true,
                            Name = "Arena Zagreb",
                            OpenedYear = 2008
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ulica Domovinskog rata 2",
                            Capacity = 12000,
                            City = "Split",
                            IsIndoor = false,
                            Name = "Arena Split",
                            OpenedYear = 2019
                        },
                        new
                        {
                            Id = 3,
                            Address = "Trg Riječke rezolucije 2",
                            Capacity = 10000,
                            City = "Rijeka",
                            IsIndoor = true,
                            Name = "Arena Rijeka",
                            OpenedYear = 2014
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseTicketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Organization")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseTicketPrice = 250m,
                            City = "Zagreb",
                            Date = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Jones vs Gustafsson",
                            Name = "UFC Fight Night Zagreb",
                            Organization = 0,
                            TicketsSold = 12850,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseTicketPrice = 180m,
                            City = "Split",
                            Date = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Ngannou vs Miocic",
                            Name = "UFC Fight Night Split",
                            Organization = 0,
                            TicketsSold = 9800,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            BaseTicketPrice = 150m,
                            City = "Rijeka",
                            Date = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main event: Cormier vs Gustafsson",
                            Name = "UFC Fight Night Rijeka",
                            Organization = 0,
                            TicketsSold = 7600,
                            Time = new TimeSpan(0, 19, 0, 0, 0),
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Fighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Organization")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Losses = 1,
                            Name = "Jon Jones",
                            Nickname = "Bones",
                            Organization = 0,
                            WeightClass = 6,
                            Wins = 26
                        },
                        new
                        {
                            Id = 2,
                            Country = "Cameroon",
                            Losses = 3,
                            Name = "Francis Ngannou",
                            Nickname = "The Predator",
                            Organization = 0,
                            WeightClass = 7,
                            Wins = 16
                        },
                        new
                        {
                            Id = 3,
                            Country = "Sweden",
                            Losses = 7,
                            Name = "Alexander Gustafsson",
                            Nickname = "The Mauler",
                            Organization = 0,
                            WeightClass = 6,
                            Wins = 18
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Losses = 3,
                            Name = "Daniel Cormier",
                            Nickname = "DC",
                            Organization = 0,
                            WeightClass = 6,
                            Wins = 22
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Losses = 4,
                            Name = "Stipe Miocic",
                            Nickname = "The Croatian Sensation",
                            Organization = 0,
                            WeightClass = 7,
                            Wins = 20
                        },
                        new
                        {
                            Id = 6,
                            Country = "Brazil",
                            Losses = 5,
                            Name = "Amanda Nunes",
                            Nickname = "The Lioness",
                            Organization = 0,
                            WeightClass = 1,
                            Wins = 21
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Championship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fighter1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fighter2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightClass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Fighter1Id");

                    b.HasIndex("Fighter2Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Championship = true,
                            EventId = 1,
                            Fighter1Id = 1,
                            Fighter2Id = 3,
                            Referee = "Herb Dean",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClass = 6
                        },
                        new
                        {
                            Id = 2,
                            Championship = false,
                            EventId = 2,
                            Fighter1Id = 2,
                            Fighter2Id = 5,
                            Referee = "John McCarthy",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClass = 7
                        },
                        new
                        {
                            Id = 3,
                            Championship = false,
                            EventId = 3,
                            Fighter1Id = 4,
                            Fighter2Id = 3,
                            Referee = "Yves Lavigne",
                            RoundLimit = 5,
                            Status = "Scheduled",
                            WeightClass = 6
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVip")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            IsVip = true,
                            LoyaltyPoints = 150,
                            MemberLevel = "Administrator",
                            Name = "admin",
                            Phone = "+385911234567"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1988, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            IsVip = false,
                            LoyaltyPoints = 200,
                            MemberLevel = "Regular User",
                            Name = "john_doe",
                            Phone = "+385912345678"
                        });
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Cart", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Event", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.Arena", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Match", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.Event", "Event")
                        .WithMany("Matches")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.Fighter", "Fighter1")
                        .WithMany("MatchesAsFighter1")
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketingSystemFightNight.Models.Fighter", "Fighter2")
                        .WithMany("MatchesAsFighter2")
                        .HasForeignKey("Fighter2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Fighter1");

                    b.Navigation("Fighter2");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Ticket", b =>
                {
                    b.HasOne("TicketingSystemFightNight.Models.Cart", "Cart")
                        .WithMany("Tickets")
                        .HasForeignKey("CartId");

                    b.HasOne("TicketingSystemFightNight.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Arena", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Cart", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Event", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.Fighter", b =>
                {
                    b.Navigation("MatchesAsFighter1");

                    b.Navigation("MatchesAsFighter2");
                });

            modelBuilder.Entity("TicketingSystemFightNight.Models.User", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
